import { Injectable, Logger } from '@nestjs/common';
import { Prisma, type AgentKind, type Platform } from '@prisma/client';
import type { AgentOutputMap } from '@contentflow/shared';
import { PrismaService } from '../prisma/prisma.service';

interface MaterializeArgs {
  runId: string;
  projectId: string;
  campaignId?: string | null;
  outputs: Partial<AgentOutputMap>;
}

export interface MaterializeResult {
  assets: number;
  schedules: number;
  analytics: number;
}

/**
 * Converts agent JSON into first-class rows — content assets, their schedules
 * and predicted metrics — so the rest of the product can edit, approve and
 * publish them without re-parsing pipeline output.
 */
@Injectable()
export class AssetMaterializerService {
  private readonly logger = new Logger(AssetMaterializerService.name);

  constructor(private readonly prisma: PrismaService) {}

  async materialize(args: MaterializeArgs): Promise<MaterializeResult> {
    const assets = [
      ...this.fromCopywriting(args),
      ...this.fromCarousels(args),
      ...this.fromScripts(args),
    ];

    if (assets.length === 0) {
      return { assets: 0, schedules: 0, analytics: 0 };
    }

    const created = await this.prisma.$transaction(async (tx) => {
      const rows = [];
      for (const asset of assets) {
        const row = await tx.contentAsset.create({ data: asset });
        // Seed version 1 so the workspace has history from the first save.
        await tx.contentVersion.create({
          data: {
            assetId: row.id,
            version: 1,
            body: row.body,
            bodyJson: row.bodyJson ?? Prisma.JsonNull,
            changeNote: 'Generated by pipeline run',
          },
        });
        rows.push(row);
      }
      return rows;
    });

    const bySlug = new Map(created.map((a) => [a.slug, a]));
    const schedules = await this.createSchedules(args, bySlug);
    const analytics = await this.createAnalytics(args);

    this.logger.log(
      `Materialized ${created.length} asset(s), ${schedules} schedule(s), ${analytics} metric(s)`,
    );
    return { assets: created.length, schedules, analytics };
  }

  private base(args: MaterializeArgs) {
    return {
      projectId: args.projectId,
      runId: args.runId,
      campaignId: args.campaignId ?? null,
    };
  }

  private fromCopywriting(args: MaterializeArgs): Prisma.ContentAssetCreateManyInput[] {
    const output = args.outputs.COPYWRITING;
    if (!output) return [];

    return output.pieces.map((piece) => ({
      ...this.base(args),
      slug: piece.slug,
      title: piece.headline,
      platform: piece.platform as Platform,
      format: piece.format,
      body: piece.body,
      bodyJson: {
        hook: piece.hook,
        cta: piece.cta,
        variants: piece.variants,
      } as Prisma.InputJsonValue,
      metadata: { headline: piece.headline } as Prisma.InputJsonValue,
      hashtags: piece.hashtags,
      characterCount: piece.body.length,
      producedBy: 'COPYWRITING' as AgentKind,
    }));
  }

  private fromCarousels(args: MaterializeArgs): Prisma.ContentAssetCreateManyInput[] {
    const output = args.outputs.CAROUSEL;
    if (!output) return [];

    return output.carousels.map((carousel) => {
      const body = carousel.slides
        .map((s) => `${s.index}. ${s.headline}\n${s.body}`)
        .join('\n\n');
      return {
        ...this.base(args),
        slug: carousel.slug,
        title: carousel.title,
        platform: carousel.platform as Platform,
        format: 'carousel',
        body,
        bodyJson: { slides: carousel.slides, caption: carousel.caption } as Prisma.InputJsonValue,
        metadata: { slideCount: carousel.slides.length } as Prisma.InputJsonValue,
        hashtags: [],
        characterCount: body.length,
        producedBy: 'CAROUSEL' as AgentKind,
      };
    });
  }

  private fromScripts(args: MaterializeArgs): Prisma.ContentAssetCreateManyInput[] {
    const output = args.outputs.SCRIPT;
    if (!output) return [];

    const platformFor = (format: string): Platform => {
      if (format === 'tiktok') return 'TIKTOK';
      if (format === 'reel') return 'INSTAGRAM';
      if (format === 'podcast' || format === 'webinar') return 'YOUTUBE';
      return 'YOUTUBE';
    };

    return output.scripts.map((script) => {
      const body = [
        `HOOK: ${script.hook}`,
        '',
        ...script.beats.map(
          (b) => `[${b.timestamp}] ${b.spoken}\n  ON-SCREEN: ${b.onScreenText}\n  VISUAL: ${b.visual}`,
        ),
        '',
        `CTA: ${script.cta}`,
      ].join('\n');

      return {
        ...this.base(args),
        slug: script.slug,
        title: script.title,
        platform: platformFor(script.format),
        format: script.format,
        body,
        bodyJson: { beats: script.beats, retentionTactics: script.retentionTactics } as Prisma.InputJsonValue,
        metadata: { durationSeconds: script.durationSeconds } as Prisma.InputJsonValue,
        hashtags: [],
        characterCount: body.length,
        producedBy: 'SCRIPT' as AgentKind,
      };
    });
  }

  private async createSchedules(
    args: MaterializeArgs,
    bySlug: Map<string, { id: string; platform: Platform }>,
  ): Promise<number> {
    const publishing = args.outputs.PUBLISHING;
    if (!publishing) return 0;

    const start = new Date();
    start.setUTCHours(0, 0, 0, 0);

    const rows: Prisma.ScheduleCreateManyInput[] = [];
    for (const entry of publishing.calendar) {
      const asset = bySlug.get(entry.slug);
      if (!asset) continue; // calendar referenced an asset no agent produced

      const [hours, minutes] = (entry.timeOfDay.match(/(\d{1,2}):(\d{2})/)?.slice(1) ?? [
        '09',
        '00',
      ]).map(Number);

      const scheduledFor = new Date(start);
      scheduledFor.setUTCDate(scheduledFor.getUTCDate() + entry.dayOffset);
      scheduledFor.setUTCHours(hours ?? 9, minutes ?? 0, 0, 0);

      rows.push({
        assetId: asset.id,
        campaignId: args.campaignId ?? null,
        platform: entry.platform as Platform,
        scheduledFor,
        timezone: publishing.timezone || 'UTC',
      });
    }

    if (rows.length === 0) return 0;
    const result = await this.prisma.schedule.createMany({ data: rows });
    return result.count;
  }

  private async createAnalytics(args: MaterializeArgs): Promise<number> {
    const analytics = args.outputs.ANALYTICS;
    if (!analytics) return 0;

    const recordedFor = new Date();
    const rows: Prisma.AnalyticsRecordCreateManyInput[] = analytics.engagementForecast.map(
      (forecast) => ({
        projectId: args.projectId,
        campaignId: args.campaignId ?? null,
        metric: 'predicted_engagement_rate',
        value: new Prisma.Decimal(parsePercent(forecast.expectedEngagementRate)),
        unit: '%',
        platform: forecast.platform as Platform,
        dimension: forecast.confidence,
        recordedFor,
        source: 'prediction',
      }),
    );

    if (rows.length === 0) return 0;
    const result = await this.prisma.analyticsRecord.createMany({ data: rows });
    return result.count;
  }
}

/** Forecasts arrive as ranges like "2.5%–4.0%"; store the midpoint. */
function parsePercent(value: string): number {
  const numbers = value.match(/\d+(\.\d+)?/g)?.map(Number) ?? [];
  if (numbers.length === 0) return 0;
  if (numbers.length === 1) return numbers[0];
  return Number(((numbers[0] + numbers[1]) / 2).toFixed(4));
}
