import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useApi } from '../../hooks/useApi';
import { getAssets } from '../../api/assets';

const TYPE_ICONS: Record<string, string> = {
  POST:'📝', CAPTION:'💬', BLOG:'📖', EMAIL:'✉️', SCRIPT:'🎬',
  CAROUSEL:'🖼', SEO:'📈', CALENDAR:'📅', DEFAULT:'📄',
};

export default function Assets() {
  const { data: assets, loading, error } = useApi(getAssets);
  const [filter, setFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState('');

  const filtered = (assets ?? []).filter(a => {
    const matchText  = !filter   || (a.title ?? a.slug ?? a.type).toLowerCase().includes(filter.toLowerCase());
    const matchType  = !typeFilter || a.type === typeFilter;
    return matchText && matchType;
  });

  const types = [...new Set((assets ?? []).map(a => a.type))];

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1 className="page-title">Assets</h1>
          <p className="page-subtitle">All content generated by your AI pipelines</p>
        </div>
      </div>

      {/* Filters */}
      <div style={{ display:'flex', gap:'var(--space-3)', marginBottom:'var(--space-6)', flexWrap:'wrap' }}>
        <input
          className="search-input"
          placeholder="Search assets…"
          value={filter}
          onChange={e => setFilter(e.target.value)}
        />
        <select className="form-select" style={{ width:'auto', minWidth:160 }} value={typeFilter} onChange={e => setTypeFilter(e.target.value)}>
          <option value="">All types</option>
          {types.map(t => <option key={t} value={t}>{t}</option>)}
        </select>
      </div>

      {loading && <div className="empty-state"><div className="spinner spinner-lg"/></div>}
      {error   && <div className="empty-state"><div className="empty-state-title text-error">{error}</div></div>}

      {!loading && !error && filtered.length === 0 && (
        <div className="empty-state">
          <div className="empty-state-icon">◉</div>
          <div className="empty-state-title">{assets?.length ? 'No results' : 'No assets yet'}</div>
          <div className="empty-state-desc">
            {assets?.length ? 'Try adjusting your search or filter.' : 'Run a pipeline to generate content assets.'}
          </div>
          {!assets?.length && <Link to="/app/pipelines" className="btn btn-primary">Run a Pipeline</Link>}
        </div>
      )}

      {!loading && filtered.length > 0 && (
        <div className="grid-3">
          {filtered.map(a => (
            <Link key={a.id} to={`/app/assets/${a.id}`} className="card" style={{ padding:'var(--space-5)', display:'block', textDecoration:'none' }}>
              <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:'var(--space-3)' }}>
                <span style={{ fontSize:'1.5rem' }}>{TYPE_ICONS[a.type] ?? TYPE_ICONS.DEFAULT}</span>
                <div style={{ display:'flex', gap:'var(--space-2)' }}>
                  <span className="badge badge-muted">v{a.version}</span>
                  {a.platform && <span className="badge badge-primary">{a.platform}</span>}
                </div>
              </div>
              <div style={{ fontWeight:600, marginBottom:'var(--space-2)', fontSize:'var(--text-sm)' }}>{a.title ?? a.slug ?? a.type}</div>
              <div style={{ fontSize:'var(--text-xs)', color:'var(--text-secondary)', lineHeight:1.7, overflow:'hidden', display:'-webkit-box', WebkitLineClamp:3, WebkitBoxOrient:'vertical' }}>
                {a.content.slice(0,180)}…
              </div>
              <div style={{ marginTop:'var(--space-3)', fontSize:'var(--text-xs)', color:'var(--text-muted)' }}>
                {new Date(a.createdAt).toLocaleDateString()}
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
